# docker-compose pull ; docker-compose up -d
####
version: "3.7"
services:
  electrumx:
    image: coindroid42/electrumx:scribe
    environment:
      DAEMON_BIN_URL: https://github.com/scribenetwork/scribe/releases/download/v0.3/scribe-ubuntu-16.04-x64.tar.gz
    restart: always  
    volumes:
      - ./data:/data
    ports:
      - "33001:33001"
      - "34001:34001"
